### ISSUE TITLE
High Sierra Config Profiles Apparently Not Being Installed from login-every

### ISSUE THREAD

**Issue by gsmc-alx** [chilcote/outset#61] opened 2018-10-01 12:03 UTC
I'm using Outset in a university lab setup, where users login using AD authentication (not sure if this is relevant), and I'm having issues with outset not installing .mobileconfig profiles for users when they login.

The user-level profiles are installed into
`/usr/local/outset/login-every`
by a pkg run by Munki.

Some users have profiles installed at login, and some do not.

It appears that scripts in the same login-every directory _are_ run at login, as they should be.

Looking in the Outset log for a user with no profiles installed, it appears, as far as Outset is concerned, that the profiles _have_ been installed successfully.

However, running
`profiles list`
as the user reveals that there are indeed no profiles installed for that user.

It's possible that Outset _is_ in fact installing the profiles, and that the OS is uninstalling them again.

MacOS 10.13.6 (High Sierra).
Outset 2.0.6.

**Comment by gsmc-alx** [comment] 2018-10-01 14:39
Should I create a script to install profiles from another location, rather than simply adding them to the login-every directory and leaving it to Outset to install them?

**Comment by chilcote** [comment] 2018-10-01 14:52
To be honest I’ve not used user-level profiles before so I can’t speak to how successful those installs are. If you want to try and put in a delay for profiles installed at login, and can show that it solves your issue, I’d be happy to accept that PR.

**Comment by gsmc-alx** [comment] 2018-10-01 15:17
Hi @chilcote,

thanks for the quick reply!

I'm going to roll a payload-free pkg with a post-install script that just sleeps for a few seconds, and stick in it the login-every directory. Since pkgs get installed before profiles, I figure that might help a bit, assuming Outset is attempting to install profiles too early at login.

I'll let you know if it helps at all.

Incidentally, what permissions should I use for pkgs to go in Outset's login-every dir.?

**Comment by chilcote** [comment] 2018-10-01 15:35
Pkgs won’t install in login context as those need root privs

**Comment by gsmc-alx** [comment] 2018-10-01 15:50
Damn. Back to the drawing board on that, then.

Is the fact pkgs can't be installed from login-every documented? I don't remember reading that..

**Comment by chilcote** [comment] 2018-10-01 15:55
You could write a script that does a `sleep 60` and then runs `profiles -I` to install the profiles maybe?

**Comment by gsmc-alx** [comment] 2018-10-01 16:02
True.

It's a shame if I have to install profiles via my own script, when Outset is supposed to be able to handle profile installation itself.

**Comment by gsmc-alx** [comment] 2018-10-01 16:11
Would it make sense to swap the order of profiles and scripts, so that Outset ran scripts first, then installed profiles?

**Comment by chilcote** [comment] 2018-10-01 18:14
Give it a shot. I probably won't have time to play with this for a few weeks sadly but if you can get a known fix we can add that

**Comment by gsmc-alx** [comment] 2018-10-01 21:08
I've forked the repo, and swapped the profiles and scripts blocks in the Python script.

Will try it tomorrow, and see if it works and more reliably.

**Comment by gsmc-alx** [comment] 2018-10-03 13:08
Would it make sense to simply install all items in alpha-numeric order, irrespective of type?

That way, users could explicitly set the execution order of items.

**Comment by chilcote** [comment] 2018-10-07 23:59
Can you post a sanitized version of the profile that you are installing?

**Comment by gsmc-alx** [comment] 2018-10-17 16:30
Having done some testing, it looks like it's a matter of the system not being ready to install profiles immediately on login.

I can't be completely sure that's the root of the problem. as I was in a bit of a hurry to get things working, and tried several things without thoroughly documenting what I did.

I ended up creating a login-every script to install the profiles, rather than having Outset install them directly. This on it's own did not solve the problem. However, it did enable me to add a pause of a controllable period, before profile installation was attempted.

Currently, the pause is 10 seconds. This seems to make profile installation much more reliable.

I'd be interested in finding out if there is any way of knowing at what point after login it becomes possible to install profiles.

**Comment by gsmc-alx** [comment] 2018-10-17 16:31
Sorry this is all a bit vague.

**Comment by gsmc-alx** [comment] 2018-10-17 16:38
Incidentally, I also have a login script run by Outset, that sets up the contents of the user's Dock.

Before adding the pause, I was finding that the default Apple applications were being inserted into the Dock, after my script had populated it.

After adding the pause, this no longer happened, which supports my supposition that Outset scripts can be sometimes be run before login scripts/agents run by the system have completed their work.

I think it's worth looking into this, or at least noting it in the docs, as scripts that manipulate preferences, as well as installing profiles may not produce the desired results because of this.

**Comment by chilcote** [comment] 2018-11-20 06:11
Did you ever find a reproducible fix for this? Was it enough to put in the pause?

**Comment by gsmc-alx** [comment] 2018-11-20 09:34
Hi,

yes, the pause seems to work, in most cases, at least.

I'd be really interested to know if there's any way to tell when it's safe to run the scripts, rather than simply blindly pausing for a number of seconds.

Maybe some flag is set when the system has run all it's login scripts?

**Comment by chilcote** [comment] 2018-11-20 17:01
It might be instructive to open a radar with apple about profiles not installing via a LaunchAgent. See what they say?

**Comment by gregneagle** [comment] 2018-11-20 17:02
"You're holding it wrong"

**Comment by gregneagle** [comment] 2018-11-20 17:04
But yes, I don't expect the developer of Outset to do the research on what other mechanisms Apple is running at login, what they do, how long they take, when it's safe to assume they are done, etc. The results of any such research are likely to be outdated very quickly since Apple isn't working under the assumption that anyone needs to know or care about this info.

**Comment by gsmc-alx** [comment] 2018-11-20 17:15
I still think it might be worth adding something to the documentation outlining possible issues with installing user-level configuration profiles at login, especially as there's an example script to do just that on the wiki.

**Comment by gregneagle** [comment] 2018-11-20 17:19
That is a "user-contributed solution", and wiki pages appear to be publicly editable, so help @chilcote out and add your notes to that page.

**Comment by erikng** [comment] 2018-11-20 18:05
Also if you're interested in the flag approach, perhaps write it yourself and issue a PR. More than likely Joe has no use case himself for this feature, so asking him to investigate and work around the issue is a bit presumptuous.

The beauty of open source is you can do the research yourself and fix it for your company and others.

Thanks,
Erik Gomez

________________________________

**Comment by chilcote** [comment] 2020-07-11 21:13
profile installs are going away anyway, so this is moot

**Closed by chilcote** 2020-07-11 21:13 UTC
